version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "8082:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - wordpress
    networks:
      - mynetwork

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password@123
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password@123
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

  wordpress:
    build:
        context: /opt/server/wordpress/
        dockerfile: /opt/server/wordpress/dockerfile  # Assuming your Dockerfile is in the root directory
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password@123
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/opt/server/
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  db_data:
  wordpress_data:

